--- #YAML:1.0
name:               Spreadsheet-ParseExcel-Stream
version:            0.08
abstract:           Simple interface to Excel data with no memory overhead
author:
    - Douglas Wilson <dougw@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Coro:                 0
    Spreadsheet::ParseExcel:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
